//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.12 at 03:40:07 PM CEST 
//


package cz.fi.muni.pa165.ws.entities.products;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Color.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Color"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BLACK"/&gt;
 *     &lt;enumeration value="WHITE"/&gt;
 *     &lt;enumeration value="RED"/&gt;
 *     &lt;enumeration value="GREEN"/&gt;
 *     &lt;enumeration value="BLUE"/&gt;
 *     &lt;enumeration value="ORANGE"/&gt;
 *     &lt;enumeration value="YELLOW"/&gt;
 *     &lt;enumeration value="AZURE"/&gt;
 *     &lt;enumeration value="MAGENTA"/&gt;
 *     &lt;enumeration value="BROWN"/&gt;
 *     &lt;enumeration value="PINK"/&gt;
 *     &lt;enumeration value="GRAY"/&gt;
 *     &lt;enumeration value="UNDEFINED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Color")
@XmlEnum
public enum Color {

    BLACK,
    WHITE,
    RED,
    GREEN,
    BLUE,
    ORANGE,
    YELLOW,
    AZURE,
    MAGENTA,
    BROWN,
    PINK,
    GRAY,
    UNDEFINED;

    public String value() {
        return name();
    }

    public static Color fromValue(String v) {
        return valueOf(v);
    }

}
