//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.28 at 07:13:23 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://muni.fi.cz/pa165/ws/entities/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cz.fi.muni.pa165.ws.entities.products;
