//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 11:03:37 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://muni.fi.cz/pa165/ws/entities/prices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cz.fi.muni.pa165.ws.entities.prices;
